### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by valgtreiz** [valgtreiz/Learning#1]
### Gaji
- [x] Cetak Daftar Gaji bulan Juli
- [x] Siapkan Daftar Gaji bulan Juli untuk TTD Kepala, Bendahara, dan semua pegawai
- [x] Siapkan Slip Gaji bulan Juli
- [x] Buat dan kirim kekurangan gaji (Harjana & Hendry Kuswara)
- [ ] Cetak dan bagikan Slip Gaji bulan Juni
- [x] TTD Daftar Gaji bulan Juni

### Kepegawaian
- [ ] Cetak TTD Penerimaan TPP bulan April dan Mei (TTD semua pegawai)
- [ ] Setting fingerprint Pak Gamal di Sewon
- [x] Monitor presensi pegawai dan siapkan dokumen pendukungnya
- [x] Siapkan nama pegawai yang akan diajukan Kenaikan Pangkat per Oktober 2022
- [x] Cetak permohonan cuti (Ammar, Aulia, Bu Rusni, Bu Feri)
- [x] Minta nomor SPT Permohonan Cuti Bulan Juni

### WBK (Kirim file ke Bu Feri)
- [ ] Perbandingan SK Penempatan CPNS dengan formasi CPNS Pergub (Excel)
- [ ] Rekap presensi pegawai Tahun 2021
- [x] _Screenshot_ pemutakhiran data pegawai ASN Memayu (Pakai akun Bu Feri)
- [x] SKP Tahun 2021
- [x] Scan Diarindu bulan Juni & Juli 2021

### Other
- [ ] Buat permohonan cuti (11 Juli)
- [x] Install ASIK di komputer kantor
