### ISSUE TITLE
Work Task List

### ISSUE THREAD

**Issue by valgtreiz** [valgtreiz/Learning#5]
### Gaji
- [x] Mutasi SIPKD Gaji (Pak Gamal)
- [x] Insentif Triwulan-II (Bu Ratih)
- [x] Slip Gaji bulan **Juli**

### Kepegawaian
- [x] TPP ke-13 (Bu Eni)
- [x] PLH Seksi Pembukuan dan Penagihan (Bu Feri)
- [x] Kirim Daftar Nomor Rekening PNS dan Tenaga Bantu

### Presensi
- [x] Jadwal Samdes dan Temaram **Juli**
- [x] SPT Odhy
- [x] Presensi Pak Wandi
- [x] Undangan Bu Yayuk
- [x] Undangan Bu Rusni (di Mbak Erni)
- [x] Cuti Odhy (11-12)

### Hardfile
- [x] TTD Penerimaan Gaji bulan Juli (Siapkan)
- [x] TTD Penerimaan TPP bulan April, Mei, Juni (Print dan Siapkan)

### Other
- [x] Kirim cuti ke huni <3
